name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST_KEY: ${{ secrets.SSH_HOST_KEY }}
      SSH_USER_HOST_LOCATION: ${{ secrets.SSH_USER_HOST_LOCATION }}
      GHP_IPESEIT: ${{secrets.GHP_IPESEIT}}
      EMAIL_PWD: ${{secrets.EMAIL_PWD}}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Prepare Quarto Project
      run: |
        sed -i "s|ghp_ipeseit|${GHP_IPESEIT}|g" ./resources/scripts/github-members.js
        sed -i "s|sender_password_value|${EMAIL_PWD}|g" ./resources/scripts/deploy.py
        docker run -v ${{ github.workspace }}:/app -w /app -u root jcfdsilva/quarto_full:latest /bin/bash -c "./resources/scripts/deploy.sh"

    - name: Deploy
      run: |
        apt-get update && apt-get install -y rsync
        which ssh-agent || (apt-get update && apt-get install -y openssh-client)
        mkdir -p ~/.ssh
        eval $(ssh-agent -s)
        echo "${SSH_PRIVATE_KEY}" | ssh-add -
        echo "${SSH_HOST_KEY}" > ~/.ssh/known_hosts
        rsync -hrvz --delete _site/* "${SSH_USER_HOST_LOCATION}"


