name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST_KEY: ${{ secrets.SSH_HOST_KEY }}
      SSH_USER_HOST_LOCATION: ${{ secrets.SSH_USER_HOST_LOCATION }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Prepare Quarto Project
      run: |
        docker run -v ${{ github.workspace }}:/app -w /app -u root -e HOME=/tmp jcfdsilva/quarto_slim:latest -c quarto render

    - name: Deploy
      run: |
        sudo apt-get update && sudo apt-get install -y rsync
        which ssh-agent || (sudo apt-get update && sudo apt-get install -y openssh-client)
        mkdir -p ~/.ssh
        eval $(ssh-agent -s)
        echo "${SSH_PRIVATE_KEY}" | ssh-add -
        echo "${SSH_HOST_KEY}" > ~/.ssh/known_hosts
        rsync -hrvz --delete _site/* "${SSH_USER_HOST_LOCATION}"


